javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac HelloWorld.java
javac src/app/Main.java
javac src.app.Main.java
javac Main.java
javac app/Main.java
javac src/app/Main.java
javac src/app/Main.java
javac src/app/Main.java
